/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventType } from '../models/event-type';
export interface EventWithDetailsDto {
  assistPlayerName?: string | null;
  comments?: string | null;
  details?: string | null;
  playerName?: string | null;
  teamId?: number;
  teamName?: string | null;
  time?: number | null;
  type?: EventType;
}
