/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GameWithDetailsDto {
  awayTeamLogo?: string | null;
  awayTeamName?: string | null;
  gameId?: number;
  gameResult?: string | null;
  homeTeamLogo?: string | null;
  homeTeamName?: string | null;
}
